Have front-page.php check is_front_page instead of is_home
wprig/wprig pull request #731
Opened 2021-07-12 20:59 UTC by idapartners

## Description
The front-page.php template currently checks whether the page is_home(). This is probably not what we want, and instead it should check is_front_page().

## List of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] This pull request relates to a ticket.
- [x] This code is tested.
- [ ] This change has been added to CHANGELOG.md
- [x] I want my code added to WP Rig.

2021-07-14 13:37 UTC, dthenley requested changes
This functionality is checking whether the front page of your site is the blog index page `is_home` or anything else.

2021-07-14 13:44 UTC, dthenley reviewed
I do agree that it should be more of a page focused call other than the blog index call. I think adding an extra if call would help.

// Use grid layout if blog index is displayed.
if (is_home() ){
	wp_rig()->print_styles( 'wp-rig-content', 'wp-rig-front-page-index' );
} elseif (is_front_page()){
	wp_rig()->print_styles( 'wp-rig-content', 'wp-rig-front-page' );
} else {
	wp_rig()->print_styles( 'wp-rig-content' );
}

2021-08-04 02:32 UTC, robruiz approved these changes

2021-08-04 02:35 UTC, robruiz commented
@idapartners - Please fix the errors that the phpcs are triggering in the Travis CI build. It looks like some improper commenting or something along those lines. Once that is addressed, I will merge this PR.

2021-08-04 02:44 UTC, robruiz requested changes
Please address commenting errors that are breaking the phpcs tests.

2021-08-04 04:47 UTC, closed without merging